### ISSUE TITLE
Firefox browser stop the download because there is virus malware , i am so scared 

### ISSUE THREAD

**Issue by trimechee** [inbasic/bulk-media-downloader#45]
Hello, i tried to donwload video from uqload paltform from this site, and i start download but Firefox browser shows me a warning that this download contains malware virus and Firefox blocks the download and firerox stops immediatly the video download : 

https://french-anime.com/animes-vf/1262-level-1-dakedo-unique-skill-de-saikyou-desu.html

without blaming anyone, is bulk-media-downloader injecting a virus into our downloads or firefox messing up and it's a false positive? it's very worrying, it's the first time it's happened to me with a downloader and we need to be reassured please, it will be good if you send a request to the firefox addons team so that your extension is parsed by firefox and bulk-media-downloader get the trust badge, thanks

**Comment by inbasic** [comment]
This downloader exclusively fetches the external resource. You need to make sure the resource is fine (you can download a virus with a downloader). The downloader itself does not modify the resource in any manner.

**Comment by trimechee** [comment]
it's very interesting, so the uqload platform could be involved? i downloaded several videos from uqload using "down them all" extension , "get them all " using pale moon browser, videodownloadhelper, FDM.....i will try to download other videos from uqload to check and try your second great extension to see if I get the same result,

 https://github.com/inbasic/turbo-download-manager-v2


 and even try microsoft edge browser, chrome..... thank you very much and thank you for all these magnificent extensions and sorry if I talked about that on your page but it was necessary and we hope we will never find again malware when downloding other uqload videos ou in other platforms :)

Please i have question : have you tried downloading this video from uqload using the extension? and you did not receive a warning that there is a virus apart from Firefox?

**Comment by trimechee** [comment]
Finally i reinstall this extension, there no more virus warning but the downloaded video  has 1ko size, so bulk media downloader can't download video from uqload and grab hls video, we hope it will be fixed, thank you
