### ISSUE TITLE
.

### ISSUE THREAD

**Issue by stuartyormak** [inbasic/bulk-media-downloader#6]

**Comment by AHMADSHARAHILY** [comment]
Search TechNet with Bing

نصائح للبحث
عملية	بناء الجملة	أمثلة
كل الشروط	TERM1 و TERM2 
TERM1 و TERM2 
TERM1 TERM2	وحدة التحكم و للإشارة 
وحدة و للإشارة 
حدة للإشارة
أي شروط	TERM1 OR TERM2 
TERM1 | TERM2	كلمة أو إكسل 
كلمة | تفوق
استبعد	TERM1 - TERM2	FindWindow - CE
مجموعة	( TERM2 TERM1 )	FindWindow AND ( CE أو MFC )
العبارة بالضبط	" العبارة "	" مجموعة أدوات مزود "
تفضيل	تفضل: [المرجع] TERM2	FindWindow تفضل: MFC

**Comment by AHMADSHARAHILY** [comment]
شكرا
