### ISSUE TITLE
Does not work with Vivaldi browser

### ISSUE THREAD

**Issue by MicroBeast** [inbasic/bulk-media-downloader#8]
ver. <= Vivaldi 1.10.845.3 (based on Chromium 58.0.3029.114).
ver. <= Bulk Media Downloader 0.1.6

Bulk Media Downloader just does not open. That's if this extension actually work at all.
It just like that since Vivaldi 2~3 versions bellow. Last time its window does open; I recall it does not even catch anything.

My first suspect, it's caused by how Vivaldi managed its own window/tab. This browser built window/tab from scratch like Opera browser. I also report the issue in Vivaldi forum.

Thank you.

**Comment by inbasic** [comment]
I just tested the extension and it works just fine in the latest version of Vivaldi

**Comment by MicroBeast** [comment]
I'm in Linux/Debian sid amd64, with Openbox WM if this matter.

Tested with clean profile also got same result.
After I click on extension icon it just show "R" icon on it, forever.
I can't find any error messages anywhere.

**Comment by inbasic** [comment]
To debug, open "chrome://extensions" in a browser tab and turn the developer mode on. Now open "background page" of the extension and see if you get a new error when opening the main window. Since you get the "R" badge text, it seems like the main window is opened successfully.

**Comment by MicroBeast** [comment]
Tried that already. No message at all. That "R" stick there all the time. If I'm lucky, it's gone after Vivaldi restart. The windows does open but can not be seen, wmctrl -l also listed.

"data/window/index.html" link in extension page also out a sure proof the window does open.

Vivaldi 1.10.845.3 (based on Chromium 58.0.3029.114) is snapshot by the way.
Today, Vivaldi Snapshot 1.10.856.16 also out, (based on Chromium 59.0.3071.51). Same, no window.

I tried Google Chrome Beta 59.0.3071.71. The window does can be seen there. Which make me believe it's Vivaldi issue. I'll ask around some people in Vivaldi forum to test Bulk Media Downloader with current snapshot, we'll see what happen.

Thank you for your response & patience.

**Comment by MicroBeast** [comment]
Confirmed by 2 users as time of this writing.
Link = https://forum.vivaldi.net/topic/17156/bulk-media-downloader-window
As I'm afraid, seem Vivaldi issue. I can't ask you to fix this just for Vivaldi of course.

I believe you could close this issue if you agree.

**Comment by inbasic** [comment]
Thanks for the follow up. So I am closing this for now. You can reopen if there is anything we could do to fix this for Vivaldi browser.

**Comment by MicroBeast** [comment]
Just to give good news.
The problem fixed per Vivaldi Snapshot 1.10.862.6
https://vivaldi.com/blog/snapshots/custom-speed-dial-thumbnails-vivaldi-browser-snapshot-1-10-862-6/
[Regression] Popup windows lack title and border (VB-28345)
